# HTTP Server
[server]
	Address     = ":9999"
	ServerRoot  = "public"
	ServerAgent = "Trunks"
	# 系统日志目录，启动，访问，异常
	LogPath     = "./log/gf-app/server"
    # 系统访问日志
    AccessLogEnabled = true
    # 系统异常日志panic
    ErrorLogEnabled  = true


# Logger.
[logger]
    Path        = "./log/gf-app/server"
    # 日志级别
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["{{", "}}"]

# Database.
[database]
    link  = "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "/tmp/log/gf-app/sql"
        Level  = "all"
        Stdout = true